# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  #desc "Runs all the tests"
  #lane :test do
  #  gradle(task: "test")
  #end

  #desc "Run lint"
  #lane :lint do
  #  gradle(task: "lint")
  #end

  desc "Deploy a new Beta build to PlayStore"
  lane :beta do
    # Read clangelog from file system
    #   note the `..`, since fastlane runs in the _fastlane_ directory
    #changelog = File.read("../Changelog.txt")
    
    #gradle(task: "clean assembleRelease")
    #gradle(task: 'assemble', build_type: 'Release')
    
    gradle(task: "clean bundleRelease")
    upload_to_play_store(track: 'beta')
    
    #crashlytics
    
    # sh "your_script.sh"
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
